---
- hosts: localhost
  gather_facts: false
  
  tasks: 
    - name: Copy file
      copy: 
        src: "{{ item }}"
        dest: ~/
      with_fileglob:
        - files/*    
        - files/.*    # include hidden files

    - name: init terraform
      shell: terraform init
      args:
        chdir: terraform/

    # - name: apply terraform script
    #   terraform:
    #     project_path: terraform/
    #     state: present
