---
- hosts: localhost
  gather_facts: false
  
  tasks: 
    - name: copy .ansible.cfg file at user's home dir
      copy: 
        src: files/.ansible.cfg
        dest: ~/

    - name: copy ssh.cfg file 
      copy:
        src: files/news-app-ssh.cfg
        dest: /tmp/

    - name: init terraform
      shell: terraform init
      args:
        chdir: terraform/
      environment:
        aws_secret_access_key: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|to_json|community.general.json_query('aws_secret_access_key') }}"
        aws_access_key_id: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|to_json|community.general.json_query('aws_access_key_id') }}"
    # - name: apply terraform script
    #   terraform:
    #     project_path: terraform/
    #     state: present
